language: java
jdk:
- oraclejdk8

install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/UI/node_modules

script: mvn clean install -q

after_success:
  - codecov
branches:
  only:
  - master
  - gerrit-integration
